#
# Step 1: Create a generic secret with the name and file given as per question:
#         i.e. kubectl create secret generic news --from-file=/opt/news.txt
# Step 2: kubectl create -f <this file>
# Step 3: Make sure the pod is in Running state
# Step 4: Verify: Open a shell to the Pod: kubectl exec -it secret-datacenter -- /bin/bash
#     In the resulting prompt, check if the secret file, news.txt, is present
#     under the mount path (i.e. /opt/apps): cat /opt/apps/news.txt
#
# For tips on getting better at Kubernetes tasks, check out the README.md
# in this folder
#
apiVersion: v1
kind: Pod
metadata:
  name: secret-devops
  labels:
    name: myapp
spec:
  volumes:
    - name: secret-volume-devops
      secret:
        secretName: ecommerce
  containers:
    - name: secret-container-devops
      image: debian:latest
      command: ["/bin/bash", "-c", "sleep 10000"]
      volumeMounts:
        - name: secret-volume-devops
          mountPath: /opt/apps
          readOnly: true
