#
# Step 1: Change the values of resource names, images and mountPaths as per question
# Step 2: kubectl create -f <this file>
# Step 3: Wait for the pod to be in running state
# Step 4: Get a shell to the first container in the pod:
#         kubectl exec -it volume-share-devops -c volume-container-devops-1 -- /bin/bash
# Step 5: In the resulting prompt, create a text file as per the question:
#         echo "Welcome to xFusionCorp Industries!" > /tmp/media/media.txt
# Step 6: Verify: Check that you are able to see this file in the second container
#         under corresponding volume mount path as they use shared volumes:
#         kubectl exec volume-share-devops -c volume-container-devops-2 -- ls /tmp/games/
#
# For tips on getting better at Kubernetes tasks, check out the README.md
# in this folder
#
apiVersion: v1
kind: Pod
metadata:
  name: volume-share-devops
  labels:
    name: myapp
spec:
  volumes:
    - name: volume-share
      emptyDir: {}
  containers:
    - name: volume-container-devops-1
      image: fedora:latest
      command: ["/bin/bash", "-c", "sleep 10000"]
      volumeMounts:
        - name: volume-share
          mountPath: /tmp/media
    - name: volume-container-devops-2
      image: fedora:latest
      command: ["/bin/bash", "-c", "sleep 10000"]
      volumeMounts:
        - name: volume-share
          mountPath: /tmp/games
