#
# Step 1: kubectl create -f <this file>
# Step 2: Wait for the pod to be in running state
# Step 3: Get a shell to the first container in the pod:
#         kubectl exec volume-share-devops --container volume-container-devops-1 -- /bin/bash
# Step 4: In the resulting prompt, create a text file as per the question:
#         echo "Welcome to xFusionCorp Industries!" > /tmp/ecommerce/ecommerce.txt
# Step 5: Verify: Check that you are able to see this file in the second container
#         under corresponding volume mount path as they use shared volumes:
#         kubectl exec volume-share-devops --container volume-container-devops-2 --
#         cat /tmp/apps/ecommerce.txt
#
# For tips on getting better at Kubernetes tasks, check out the README.md
# in this folder
#
apiVersion: v1
kind: Pod
metadata:
  name: volume-share-devops
  labels:
    name: myapp
spec:
  volumes:
    - name: volume-share
      emptyDir: {}
  containers:
    - name: volume-container-devops-1
      image: centos:latest
      command: ["/bin/bash", "-c", "sleep 10000"]
      volumeMounts:
        - name: volume-share
          mountPath: /tmp/ecommerce
    - name: volume-container-devops-2
      image: centos:latest
      command: ["/bin/bash", "-c", "sleep 10000"]
      volumeMounts:
        - name: volume-share
          mountPath: /tmp/apps
