#
# Step 1: Simply save this file as playbook.yml in the required folder
# Step 2: Run `ansible-playbook -i inventory playbook.yml`
# Step 3: Verify: Check that the files are created by running
#         ansible all -a "ls -ltr /opt/data/" -i inventory
#
# For tips on getting better at Ansible tasks, check out the README.md
# in this folder
#
- name: Create file and set ACL in Host 1
  hosts: stapp01
  become: yes
  tasks:
    - name: Create the blog.txt on stapp01
      file:
        path: /opt/data/blog.txt
        state: touch
    - name: Set ACL for blog.txt
      acl:
        path: /opt/data/blog.txt
        entity: tony
        etype: group
        permissions: r
        state: present
- name: Create file and set ACL in Host 2
  hosts: stapp02
  become: yes
  tasks:
    - name: Create the story.txt on stapp02
      file:
        path: /opt/data/story.txt
        state: touch
    - name: Set ACL for story.txt
      acl:
        path: /opt/data/story.txt
        entity: steve
        etype: user
        permissions: rw
        state: present
- name: Create file and set ACL in Host 3
  hosts: stapp03
  become: yes
  tasks:
    - name: Create the media.txt on stapp03
      file:
        path: /opt/data/media.txt
        state: touch
    - name: Set ACL for media.txt
      acl:
        path: /opt/data/media.txt
        entity: banner
        etype: group
        permissions: rw
        state: present
